## Automated pre-release on push to master.

name: RetDec pre-release

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
        # We want to use msys2 bash on Windows.
      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'

      - name: "Build & test"
        if: runner.os != 'Windows'
        run: |
          mkdir artifact
          mkdir install
          echo "done!" > install/${{ runner.os }}.log
          cd install
          tar -cvJf RetDec-${{ runner.os }}-Release.tar.xz *
          mv *.tar.xz ../artifact

      - name: "Build & test windows"
        if: runner.os == 'Windows'
        run: |
          choco install --no-progress 7zip
          mkdir artifact
          mkdir install
          echo "done!" > install/${{ runner.os }}.log
          cd install
          7z a RetDec-${{ runner.os }}-Release.7z *
          mv *.7z ../artifact
        shell: 'msys2 {0}'

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: artifact/*

  pre-release:
    strategy:
      matrix:
        os:
          - ubuntu-latest

    name: "Pre Release"

    runs-on: ${{ matrix.os }}
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Archive Artifacts
        uses: actions/download-artifact@v3
        with:
          path: install

      - name: Pack Artifacts
        run: |
          for i in $(ls .); do
            tar -cvzf ../$i.tar.gz $i
          done
        working-directory: install

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            LICENSE.txt
            CHANGELOG.md
            some_file.txt
            *.tar.gz
