## Automated pre-release on push to master.

name: RetDec pre-release

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: "Build & test"
        run: |
          mkdir install
          echo "done!" > install/${{ runner.os }}.log

      - name: Archive Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: RetDec-${{ runner.os }}-Release
          path: install

  pre-release:
    strategy:
      matrix:
        os:
          - ubuntu-latest

    name: "Pre Release"

    runs-on: ${{ matrix.os }}
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Archive Artifacts
        uses: actions/download-artifact@v3
        with:
          path: install

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            LICENSE.txt
            CHANGELOG.md
            some_file.txt
            install/*
