## Automated pre-release on push to master.

name: RetDec pre-release

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  pre-release:
    strategy:
      matrix:
        os:
          - ubuntu-latest

    name: "Pre Release"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: "Build & test"
        run: |
          echo "done!" > ${{ runner.os }}.log

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref }}
          generate_release_notes: true
          files: |
            LICENSE.txt
            CHANGELOG.md
            some_file.txt
            ${{ runner.os }}.log
