## Automated pre-release on push to master.

name: RetDec pre-release

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-2019
          - macos-11

    name: "Pre Release"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: "Build & test"
        run: |
          echo "done!" > ${{ runner.os }}.log

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            CHANGELOG.md
            some_file.txt
            ${{ runner.os }}.log
